apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-cicd
  labels:
    app: container-cicd
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: container-cicd
      
  template:
    metadata:
      labels:
        app: container-cicd
        tier: container-cicd
    spec:
      containers:
        - name: container-cicd
          image: ganeshmete11/container-cicd:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8060
            name: container-cicd


---
apiVersion: v1
kind: Service
metadata:
  name: container-cicd
  labels:
    app: container-cicd
spec:
  ports:
    - port: 8060
      targetPort: 8060
  selector:
    app: container-cicd
    tier: container-cicd
  type: LoadBalancer 